### ISSUE TITLE
textures/models not loading

### ISSUE THREAD

**Issue by raoul1234** [2xsaiko/rswires#18]
I downloaded the 1.16.5 version (running 1.16.4). And noticed the following issues:
-Textures don't load in the player inventory.
-Placed models don't load.

The mechanics seem to work and not be affected.
Below you'll find some images to elaborate the issue:
![image](https://user-images.githubusercontent.com/15872123/127315611-86d2e0e6-2f3f-4632-976b-6732efef0812.png)

![image](https://user-images.githubusercontent.com/15872123/127315931-acefd3fd-12b4-4020-b135-bbb836ececba.png)

List of mods:
cloth-config-4.11.26-fabric.jar
ezpas-1.2.3-1.16.2.jar
fabric-api-0.37.1+1.16.jar
Fabric-language-kotlin-1.6.2+kotlin.1.5.20.jar
iris-mc1.16.5-1.1.0.jar
modmenu-1.16.11.jar
okzoomer-4.0.1+1.16.2.jar
RebornCore-1.16-4.7.3+build.136.jar
RoughlyEnoughItems-5.12.248.jar
rswires-4.10.2.jar
TechReborn-1.16-3.8.4+build.236.jar

Minecraft version 1.16.4 With Fabric 0.11.6

**Comment by dblsaiko** [comment]
Please send the game log.

**Comment by raoul1234** [comment]
Hi,

Please find the Log attached

[2021-07-28-7.log](https://github.com/2xsaiko/rswires/files/6896007/2021-07-28-7.log)

**Comment by dblsaiko** [comment]
> 	- sodium@0.2.0+IRIS3-rev.2c3e7cc
> [21:27:41] [Worker-Main-13/ERROR]: Could not find Renderer API implementation. Rendering for RSWires wires will not be available.

You have Sodium installed, that doesn't provide a Fabric Renderer API implementation. Try installing Indium which should fix that.

**Comment by raoul1234** [comment]
Sorry for the late response!

Thank you! that fixed it.

**Comment by dblsaiko** [comment]
Alright, nice.
