### ISSUE TITLE
Comparator side input doesn't accept alloy wire

### ISSUE THREAD

**Issue by copygirl** [2xsaiko/rswires#4]
Minecraft: `1.16.1`
RSWires: `4.9.0`

It looks like the wire connects to the comparator's side, but neither in compare nor subtract mode does it actually affect the comparator's output. I noticed this while trying to make a comparator clock. One temporary workaround is to replace the wire connected to the side with redstone dust.

### To Reproduce...
![2020-08-26_08 07 31](https://user-images.githubusercontent.com/272586/91267292-59ad3400-e773-11ea-9a5e-f63d3a59e5a7.png)

### Expected Output
![2020-08-26_08 07 38](https://user-images.githubusercontent.com/272586/91267295-5b76f780-e773-11ea-9f48-9cc06e34836c.png)

**Comment by dblsaiko** [comment]
Looks like comparators take strong power from the sides, and red alloy wire only provides strong power downwards. It's hardcoded to work correctly for redstone dust in the comparator code. This is gonna need some weird hacks to fix.

**Comment by copygirl** [comment]
What makes the wire visually connect to the side of the comparator? Can you use that to affect whether strong power is applied to the block, whether it specifically is a comparator or not?

edit: Ah well, if it's hardcoded to work that way ... I suppose redstone doesn't provide strong power to blocks it visually connects to, either? Then yeah, the wire should probably work the same.

**Comment by dblsaiko** [comment]
Yeah I just hardcoded it to provide strong power to comparators only (see 6356a06), now it should work the same as redstone dust. And no, I believe the redstone wire connections is only a visual thing and it provides weak power regardless of if it appears connected or not.
