### ISSUE TITLE
Infinite loading and incompatibility with Sodium Mod

### ISSUE THREAD

**Issue by RodrigoZXMota** [2xsaiko/rswires#5]
### Expected Behavior
The game should open fine, no errors

### Actual Behavior
When loading minecraft with Sodium + RSWires all letters are replaced by squares and the game endlessly loops between Mojang Loading Screen and Menu, turning impossivle even starting a world.

### Reproduction Steps
I'm using the latest build of fabric at the time for **>1.16.2<** 

1. Install Sodium Mc.1.16.3-0.1.0.jar
2. Install RSWires rswires-4.9.1.jar
3. Error occours

### System Information

- Java Version: Latest java
- CPU: Intel i7 4770
- GPU: GTX 750 Ti
(But error happens in other pc's aswell)

**Comment by dblsaiko** [comment]
Sodium doesn't implement the Fabric Rendering API which this mod uses for the wire models. I can't fix this on my side (except maybe add a better error message).
